### ISSUE TITLE
Available host definitions

### ISSUE THREAD

**Issue by boverby** [gtalusan/PADIIoTStamp#3]
Thank you for this repo. it has made all the difference in getting rtl8710 to be programmable.  I could not install on debian 8 ( 3.16.0-4-amd64) until I made local copy of repo and modified the systems stanza under tools to include more host options in https://github.com/gtalusan/PADIIoTStamp/blob/master/release/package_padiiotstamp_index.json

I am starting on movement to raspberry pi as host later today, so I might be adding arm-linux-gnueabihf, but I have not tried it yet.

Can these be added? or since they are just text files, can it be wild-carded for all hosts?

Thanks again

# diff package_padiiotstamp_index.json package_padiiotstamp_index.json.dist
48,75d47
<             {
<               "host": "i686-linux-gnu",
<               "archiveFileName": "openocd_tools-0.0.1.tar.gz",
<               "url": "https://github.com/gtalusan/PADIIoTStamp/raw/master/release/openocd_tools-0.0.1.tar.gz",
<               "checksum": "SHA-256:69b05f075118c39f26281e15055ae0d0cd64b188daeca724386bf9fb7dcaf3e7",
<               "size": "11572"
<             },
<             {
<               "host": "x86_64-linux-gnu",
<               "archiveFileName": "openocd_tools-0.0.1.tar.gz",
<               "url": "https://github.com/gtalusan/PADIIoTStamp/raw/master/release/openocd_tools-0.0.1.tar.gz",
<               "checksum": "SHA-256:69b05f075118c39f26281e15055ae0d0cd64b188daeca724386bf9fb7dcaf3e7",
<               "size": "11572"
<             },
<             {
<               "host": "i686-pc-linux-gnu",
<               "archiveFileName": "openocd_tools-0.0.1.tar.gz",
<               "url": "https://github.com/gtalusan/PADIIoTStamp/raw/master/release/openocd_tools-0.0.1.tar.gz",
<               "checksum": "SHA-256:69b05f075118c39f26281e15055ae0d0cd64b188daeca724386bf9fb7dcaf3e7",
<               "size": "11572"
<             },
<             {
<               "host": "x86_64-pc-linux-gnu",
<               "archiveFileName": "openocd_tools-0.0.1.tar.gz",
<               "url": "https://github.com/gtalusan/PADIIoTStamp/raw/master/release/openocd_tools-0.0.1.tar.gz",
<               "checksum": "SHA-256:69b05f075118c39f26281e15055ae0d0cd64b188daeca724386bf9fb7dcaf3e7",
<               "size": "11572"
<             },

**Comment by gtalusan** [comment]
Not too sure.  Fine with the copy & paste.  Make a patch.

**Comment by boverby** [comment]
first time doing this:

let me know if it is wrong

**Comment by boverby** [comment]
btw, no success on running on raspberry pi because no  support for arm-linux-gnueabihf in Ameba8195.  I tried replacing json file with locally recompiled ameba_tools.tar.gz and gcc from arduino, but no joy. I'm back to x86 until the project is over.

**Comment by boverby** [comment]
I can't tell if the email attachment made it's way to you, so here is a gist of the file

https://gist.github.com/boverby/c35cb1ac9f6310719c1c9b25e8ea0354

**Comment by gtalusan** [comment]
You can make a pull request instead of the gist
